bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: hwzxugaTQfBagb9gJTj9S0BW+q65rOb8JcVMMsBO/sJEeGi16Hc79Wx0vzjlC1OaTaA0ijXFbhFyW3T64vMSpOXK0gpRGcVY4PTu5JFKMvvRT/Rw/yc3EMNSyISrB7rx70Tq9raCjp6gf6jvYjqn78vklTD1btiyd6NLESrDktAN9czid3qLtrabvPLskeCheCJDaykAhfU1AMyyJgJDxj0a8Q1DKGf7LgUMrj+f/p5JixumWTrj5t/bHEf3ROqBtoY2uZj0hBaTyz5D7fB2sMPoeU+r8vwM4oREsz4w9U5UskhQJUpHJsxk6fBYZXMP5y8nwqmbO3ss1goKCypv+Y7hrOtLh4/0B0jRH+cbBJnFNGe7rvCzKJWnrXxl+/ulMAHoqzTSNRIA8WW9pb4rI2JyeQ3WgWS+IivsssBMaIcD8c/wPRgU27Ef4HjosGEw8X9FvY9y5fA3z+OkE7/twj5VCGUeioxGhUuRWsfXI2wkUyeD3OpXJhA5wQ/Kj1GVshC+jBafevQcvY3cw+fiHrJ7VYFBesjOzy2JYYvqZDjrV3J7Kiq269iLwfxf7/vsiLlKUAZ4YtRGyYGTZuXGE1+oHtfXSHud3VWc74mevFTSZ7fCxrI7FPBZDatfjVBjgwqVcYnPg9Y2jXkI7nvbEWR7PhCdFZQMmYx3DQ3pglU=
conda_forge_output_validation: true
